{{/*
Copyright 2019-present Open Networking Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{ tuple "enb2" . | include "oaisim.service_account" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enb2
  labels:
{{ tuple "enb2" . | include "oaisim.metadata_labels" | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ tuple "enb2" . | include "oaisim.metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple "enb2" . | include "oaisim.metadata_labels" | indent 8 }}
    spec:
    {{- if .Values.nodeSelectors.enabled }}
      nodeSelector:
        {{ .Values.nodeSelectors.enb.label }}: {{ .Values.nodeSelectors.enb.value }}
    {{- end }}
      serviceAccountName: enb2
      hostNetwork: true
      initContainers:
        - name: enb2-dep-check
          image: {{ .Values.images.tags.dep_check | quote }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: COMMAND
              value: "echo done"
            - name: DEPENDENCY_POD_JSON
              value: '[{"labels": {"app": "mme"}, "requireSameNode": false}]'
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
        - name: enb2-init
          image: {{ .Values.images.tags.enb | quote }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          command:
            - /opt/oaisim/enb/scripts/enb2-init.sh
          env:
            - name: enb2_LOCAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: script
              mountPath: /opt/oaisim/enb/scripts/enb2-init.sh
              subPath: enb2-init.sh
            - name: config
              mountPath: /opt/oaisim/enb/config
            - name: pod-share
              mountPath: /etc/oaisim/enb
      containers:
        - name: enb2
          image: {{ .Values.images.tags.enb | quote }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
            privileged: true
          command:
            - /opt/oaisim/enb/scripts/enb2-run.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /opt/oaisim/enb/scripts/enb2-run.sh
                  - stop
          env:
            - name: enb2_LOCAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: script
              mountPath: /opt/oaisim/enb/scripts/enb2-run.sh
              subPath: enb2-run.sh
            - name: pod-share
              mountPath: /etc/oaisim/enb
      volumes:
        - name: config
          configMap:
            name: enb
            defaultMode: 420
        - name: script
          configMap:
            name: enb
            defaultMode: 493
        - name: pod-share
          emptyDir: {}
